=== stasiekz/PolishReadabilityChecker/third_party/corpus2/doc/xcesAnaIPI.dtd
<!--                                                          -->
<!--                                                          -->
<!--                Corpus Encoding Standard                  -->
<!--                                                          -->
<!--                          CES                             -->
<!--                                                          -->
<!--         Encoding conventions for annotated data          -->
<!--                                                          -->
<!--                                                          -->
<!--         Modified for the IPI PAN corpus                  -->
<!--         Version IPI-1.6                                  -->
<!--                                                          -->
<!--                                                          -->
<!--                                                          -->
<!--                                                          -->
<!--                                                          -->
<!--
     Original Date: 1996/08/05 19:07:30 
     Original Revision: 1.11 
     Author of 1.11: Patrice Bonhomme

     $Id: xcesAnaIPI.dtd,v 1.1.1.1 2007/11/08 15:26:49 adamp Exp $
*    $Log: xcesAnaIPI.dtd,v $
*    Revision 1.1.1.1  2007/11/08 15:26:49  adamp
*    Spejd
*
*    Revision 1.1  2007/10/20 13:11:39  adamp
*    *** empty log message ***
*
*    Revision 1.6  2006/06/03 12:53:28  adamp
*    Updated version number of xcesAnaIPI.dtd.
*
*    Revision 1.5  2006/06/03 12:45:41  adamp
*    Simplified.
*
*    Revision 1.2  2006/06/03 12:33:13  adamp
*    Changed name from doc2ana.sh to index.morph.sh.
*
*    Revision 1.1  2006/06/03 11:43:59  adamp
*    *** empty log message ***
*
*    Revision 1.4  2006/02/03 14:00:50  adamp
*    Corresponding change of version number (to 1.3).
*
*    Revision 1.3  2006/02/03 13:59:03  adamp
*    Changed (tok|ns)+ to (tok|ns)* - let's hope that Poliqarp can deal with empty chunks...
*
*    Revision 1.2  2004-03-16 19:00:48  adamp
*    ATTLIST for lex was defined twice, so I've removed the first
*    definition.  This caused version change to IPI-1.2 (maybe it shouldn't
*    have, but just to be on the safe side).
*
*    Revision 1.1.1.1  2004/03/10 19:21:29  adamp
*    x2XCES converters for the IPI PAN corpus
*
*    Revision 1.14  2004/03/01 16:00:48  adamp
*    New version: 'IPI-1.1'.
*
*    Revision 1.13  2004/03/01 15:58:05  adamp
*    Only typos in comments.
*
*    Revision 1.12  2004/03/01 13:58:55  adamp
*    PB's modifications: the value of 'lang' is CDATA now, and the locus of
*    xmlns:xlink changed.
*
*    Revision 1.11  2004/03/01 10:55:46  adamp
*    PB's modifications.
*
*    Revision 1.11  2004/03/01 01:15:30  piotr
*    Added fully specified xmlns:xlink (to make the xlink namespace legal)
*    and the xml:base attribute for use in <chunkList>
*
*    $Log: xcesAnaIPI.dtd,v $
*    Revision 1.1.1.1  2007/11/08 15:26:49  adamp
*    Spejd
*
*    Revision 1.1  2007/10/20 13:11:39  adamp
*    *** empty log message ***
*
*    Revision 1.6  2006/06/03 12:53:28  adamp
*    Updated version number of xcesAnaIPI.dtd.
*
*    Revision 1.5  2006/06/03 12:45:41  adamp
*    Simplified.
*
*    Revision 1.2  2006/06/03 12:33:13  adamp
*    Changed name from doc2ana.sh to index.morph.sh.
*
*    Revision 1.1  2006/06/03 11:43:59  adamp
*    *** empty log message ***
*
*    Revision 1.4  2006/02/03 14:00:50  adamp
*    Corresponding change of version number (to 1.3).
*
*    Revision 1.3  2006/02/03 13:59:03  adamp
*    Changed (tok|ns)+ to (tok|ns)* - let's hope that Poliqarp can deal with empty chunks...
*
*    Revision 1.2  2004-03-16 19:00:48  adamp
*    ATTLIST for lex was defined twice, so I've removed the first
*    definition.  This caused version change to IPI-1.2 (maybe it shouldn't
*    have, but just to be on the safe side).
*
*    Revision 1.1.1.1  2004/03/10 19:21:29  adamp
*    x2XCES converters for the IPI PAN corpus
*
*    Revision 1.14  2004/03/01 16:00:48  adamp
*    New version: 'IPI-1.1'.
*
*    Revision 1.13  2004/03/01 15:58:05  adamp
*    Only typos in comments.
*
*    Revision 1.12  2004/03/01 13:58:55  adamp
*    PB's modifications: the value of 'lang' is CDATA now, and the locus of
*    xmlns:xlink changed.
*
*    Revision 1.11  2004/03/01 10:55:46  adamp
*    PB's modifications.
*
*    Revision 1.10  2004/02/27 22:38:09  adamp
*    Wyrzucone atrybuty xml..., dodany element <ns> (no space).
*
*    Revision 1.9  2004/02/25 23:00:34  adamp
*    Changes in comments only.
*
*    Revision 1.8  2004/02/25 16:36:50  adamp
*    Re-introducing various modifications by PB.
*
*    Revision 1.7  2004/02/22 19:10:58  adamp
*    Only minor changes in comments.
*
*    Revision 1.6  2004/02/12 15:43:47  adamp
*    *** empty log message ***
*
*    Revision 1.5  2004/02/11 22:38:47  adamp
*    Typo.
*
*    Revision 1.4  2004/02/10 17:51:51  adamp
*    Wersja zawierająca <par> (tak jak w oryginalnym XCES, inaczej niż w
*    wersji Piotrka Bańskiego).
*
*    Revision 1.3  2004/02/10 17:18:09  adamp
*    No real change, just testing CVS.
*
*    Revision 1.2  2004/02/10 17:17:30  adamp
*    Added xmlns.

  This is a modification of the original CES DTD designed for use with
  the IPI PAN Corpus.  Created by Adam Przepiórkowski, on the basis of
  ealier modifications by Piotr Bański, cf. PB (who's the author of
  the vast majority of changes, as of 9th February 2004).

                                                              -->

<!--                  Global attributes                       -->

<!-- Modification by Piotr Bański: -->
<!-- The addition of the xlink:href attribute below. -->
<!-- PB, 010304: 'lang IDREFS' zmienione na 'lang CDATA'. -->
<!ENTITY % a.global '
	id		ID                  #IMPLIED
	n		CDATA               #IMPLIED
	xml:lang	CDATA               #IMPLIED
        xlink:href      CDATA               #IMPLIED
	lang		CDATA               #IMPLIED'		>

<!-- Modification by PB: adding xlink:... attributes.  Also xml:base.  -->
<!ENTITY % a.ana '%a.global;
        xml:base        CDATA               #IMPLIED
	type		CDATA               #IMPLIED
	wsd		CDATA               #IMPLIED'		>
 

<!ELEMENT cesAna	(cesHeader?, chunkList)			>
<!-- Modification by PB: xmlns:xlink.  -->
<!ATTLIST cesAna	%a.ana;                         
	doc		CDATA		#IMPLIED
        xmlns:xlink     CDATA           "http://www.w3.org/1999/xlink"
	version		CDATA		#REQUIRED		>

<!ENTITY % xces.header SYSTEM 'xheaderIPI.elt'                       >
%xces.header;

<!ELEMENT chunkList     (chunk)+                           >
<!ATTLIST chunkList          %a.ana;                            >

<!-- AP: Chunks contain either smaller chunks or tokens + no white space -->
<!-- markers. -->
<!-- AP: Changed + to * - let's hope that Poliqarp can deal with empty chunks... -->
<!ELEMENT chunk         ((tok|ns)* | chunk+)                 >
<!-- PB's modification: no attributes 'doc', 'from' and 'to'. -->
<!ATTLIST chunk              %a.ana;                   >

<!-- AP: elements 'par' and 's' disappear; instead, there chunks of type -->
<!-- 's' and 'p'. --> 


<!-- PB's modification (and comment) -->
<!--
threw out the disamb element - it will be an attribute now
more simplification:
eliminated msds, cause we use ctags for them; guarantee at least one lex;
-->
<!ELEMENT tok           (orth, lex+)              >

<!-- PB's modification: -->
<!-- Removed attributes 'from' and 'to'. -->
<!ATTLIST tok                %a.ana;
          class              CDATA               #IMPLIED >

<!-- AP: Adding a 'no white space between tokens' marker: -->
<!ELEMENT ns           EMPTY                              >

<!ELEMENT orth          (#PCDATA)                          >
<!ATTLIST orth               %a.ana;                            >

<!-- PB's modification (and comment): -->
<!--
msd removed for simplicity, we use msds as ctags
and ctags are grouped around a unique base (note: uniqueness of the base is not
guaranteed by the DTD)
-->
<!ELEMENT lex           (base, ctag+)                 >
<!-- AP: gotten rid of spurious attlist for lex. -->
<!-- <!ATTLIST lex                %a.ana;                      > -->


<!-- Modification by Piotr Bański: -->
<!-- duplicated 'disamb' with 'human', indicating hand-checked bits -->
<!ATTLIST lex                %a.ana;
          disamb        (1 | 0)                   #IMPLIED
          human         (1 | 0)                   #IMPLIED         >

<!ELEMENT base          (#PCDATA)                          >
<!ATTLIST base               %a.ana;                            >

<!-- The msd element removed (by PB). -->

<!-- PB's modification and comment: -->
<!-- added the disamb attribute here -->
<!ELEMENT ctag          (#PCDATA)                          >
<!ATTLIST ctag               %a.ana;                            >

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/match/lexicon/cclmatch-1.out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <sentence>
   <tok>
    <orth>To</orth>
    <lex><base>ten</base><ctag>adj</ctag></lex>
    <lex><base>to</base><ctag>noun</ctag></lex>
    <lex><base>to</base><ctag>other</ctag></lex>
    <lex><base>to</base><ctag>qub</ctag></lex>
    <lex><base>to</base><ctag>verb</ctag></lex>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>już</orth>
    <lex><base>już</base><ctag>qub</ctag></lex>
    <ann chan="QP" head="1">1</ann>
   </tok>
   <tok>
    <orth>dziś</orth>
    <lex><base>dziś</base><ctag>noun</ctag></lex>
    <lex><base>dziś</base><ctag>qub</ctag></lex>
    <ann chan="QP">1</ann>
   </tok>
   <tok>
    <orth>wcale</orth>
    <lex><base>wcale</base><ctag>qub</ctag></lex>
    <ann chan="QP">1</ann>
   </tok>
   <tok>
    <orth>nie</orth>
    <lex><base>nie</base><ctag>other</ctag></lex>
    <lex><base>nie</base><ctag>qub</ctag></lex>
    <lex><base>on</base><ctag>other</ctag></lex>
    <ann chan="QP">1</ann>
   </tok>
   <tok>
    <orth>jest</orth>
    <lex><base>być</base><ctag>verb</ctag></lex>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>śmieszne</orth>
    <lex><base>śmieszny</base><ctag>adj</ctag></lex>
    <ann chan="QP">0</ann>
   </tok>
   <ns/>
   <tok>
    <orth>!</orth>
    <lex><base>!</base><ctag>interp</ctag></lex>
    <ann chan="QP">0</ann>
   </tok>
  </sentence>
  <sentence>
   <tok>
    <orth>To</orth>
    <lex><base>ten</base><ctag>adj</ctag></lex>
    <lex><base>to</base><ctag>noun</ctag></lex>
    <lex><base>to</base><ctag>other</ctag></lex>
    <lex><base>to</base><ctag>qub</ctag></lex>
    <lex><base>to</base><ctag>verb</ctag></lex>
    <ann chan="PrepNP">0</ann>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>dla</orth>
    <lex><base>dla</base><ctag>other</ctag></lex>
    <ann chan="PrepNP" head="1">1</ann>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>niego</orth>
    <lex><base>on</base><ctag>other</ctag></lex>
    <ann chan="PrepNP">1</ann>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>i</orth>
    <lex><base>i</base><ctag>other</ctag></lex>
    <lex><base>i</base><ctag>qub</ctag></lex>
    <ann chan="PrepNP">0</ann>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>dla</orth>
    <lex><base>dla</base><ctag>other</ctag></lex>
    <ann chan="PrepNP" head="1">2</ann>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>nas</orth>
    <lex><base>NASA</base><ctag>noun</ctag></lex>
    <lex><base>my</base><ctag>other</ctag></lex>
    <ann chan="PrepNP">2</ann>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>wręcz</orth>
    <lex><base>wręcz</base><ctag>qub</ctag></lex>
    <lex><base>wręczyć</base><ctag>verb</ctag></lex>
    <ann chan="PrepNP">0</ann>
    <ann chan="QP" head="1">1</ann>
   </tok>
   <tok>
    <orth>nie</orth>
    <lex><base>nie</base><ctag>other</ctag></lex>
    <lex><base>nie</base><ctag>qub</ctag></lex>
    <lex><base>on</base><ctag>other</ctag></lex>
    <ann chan="PrepNP">0</ann>
    <ann chan="QP">1</ann>
   </tok>
   <tok>
    <orth>do</orth>
    <lex><base>do</base><ctag>noun</ctag></lex>
    <lex><base>do</base><ctag>other</ctag></lex>
    <ann chan="PrepNP" head="1">3</ann>
    <ann chan="QP">0</ann>
   </tok>
   <tok>
    <orth>pomyślenia</orth>
    <lex><base>pomyślenie</base><ctag>noun</ctag></lex>
    <lex><base>pomyśleć</base><ctag>noun</ctag></lex>
    <ann chan="PrepNP">3</ann>
    <ann chan="QP">0</ann>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
    <ann chan="PrepNP">0</ann>
    <ann chan="QP">0</ann>
   </tok>
  </sentence>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/match/postcond3/cclmatch2.out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <sentence>
   <tok>
    <orth>Początek</orth>
    <lex><base>początek</base><ctag>subst:sg:nom:m3</ctag></lex>
    <lex><base>początek</base><ctag>subst:sg:acc:m3</ctag></lex>
    <ann chan="NP">0</ann>
   </tok>
   <tok>
    <orth>nowego</orth>
    <lex><base>nowy</base><ctag>adj:sg:gen:m1:pos</ctag></lex>
    <lex><base>nowy</base><ctag>adj:sg:acc:m1:pos</ctag></lex>
    <lex><base>nowy</base><ctag>adj:sg:gen:m2:pos</ctag></lex>
    <lex><base>nowy</base><ctag>adj:sg:acc:m2:pos</ctag></lex>
    <lex><base>nowy</base><ctag>adj:sg:gen:m3:pos</ctag></lex>
    <lex><base>nowy</base><ctag>adj:sg:gen:n:pos</ctag></lex>
    <ann chan="NP" head="1">1</ann>
   </tok>
   <tok>
    <orth>zdania</orth>
    <lex><base>zdanie</base><ctag>subst:sg:gen:n</ctag></lex>
    <lex><base>zdanie</base><ctag>subst:pl:nom:n</ctag></lex>
    <lex><base>zdanie</base><ctag>subst:pl:acc:n</ctag></lex>
    <lex><base>zdanie</base><ctag>subst:pl:voc:n</ctag></lex>
    <lex><base>zdać</base><ctag>ger:sg:gen:n:perf:aff</ctag></lex>
    <ann chan="NP">1</ann>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
    <ann chan="NP">0</ann>
   </tok>
  </sentence>
  <sentence>
   <tok>
    <orth>Nowy</orth>
    <lex><base>nowy</base><ctag>adj:sg:nom:m1:pos</ctag></lex>
    <lex><base>nowy</base><ctag>adj:sg:nom:m2:pos</ctag></lex>
    <lex><base>nowy</base><ctag>adj:sg:nom:m3:pos</ctag></lex>
    <lex><base>nowy</base><ctag>adj:sg:acc:m3:pos</ctag></lex>
    <ann chan="NP">0</ann>
   </tok>
   <tok>
    <orth>początek</orth>
    <lex><base>początek</base><ctag>subst:sg:nom:m3</ctag></lex>
    <lex><base>początek</base><ctag>subst:sg:acc:m3</ctag></lex>
    <ann chan="NP">0</ann>
   </tok>
   <tok>
    <orth>starego</orth>
    <lex><base>stary</base><ctag>adj:sg:gen:m1:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:acc:m1:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:gen:m2:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:acc:m2:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:gen:m3:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:gen:n:pos</ctag></lex>
    <ann chan="NP" head="1">1</ann>
   </tok>
   <tok>
    <orth>zdania</orth>
    <lex><base>zdanie</base><ctag>subst:sg:gen:n</ctag></lex>
    <lex><base>zdanie</base><ctag>subst:pl:nom:n</ctag></lex>
    <lex><base>zdanie</base><ctag>subst:pl:acc:n</ctag></lex>
    <lex><base>zdanie</base><ctag>subst:pl:voc:n</ctag></lex>
    <lex><base>zdać</base><ctag>ger:sg:gen:n:perf:aff</ctag></lex>
    <ann chan="NP">1</ann>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
    <ann chan="NP">0</ann>
   </tok>
  </sentence>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/tag/unify/kobieta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <chunk type="s">
   <tok>
    <orth>Kobieta</orth>
    <lex><base>kobieta</base><ctag>subst:sg:nom:f</ctag></lex>
   </tok>
   <tok>
    <orth>nie</orth>
    <lex><base>nie</base><ctag>qub</ctag></lex>
    <lex><base>on</base><ctag>ppron3:sg:acc:n:ter:praep</ctag></lex>
    <lex><base>on</base><ctag>ppron3:pl:acc:m2:ter:praep</ctag></lex>
    <lex><base>on</base><ctag>ppron3:pl:acc:m3:ter:praep</ctag></lex>
    <lex><base>on</base><ctag>ppron3:pl:acc:f:ter:praep</ctag></lex>
    <lex><base>on</base><ctag>ppron3:pl:acc:n:ter:praep</ctag></lex>
   </tok>
   <tok>
    <orth>bita</orth>
    <lex><base>bity</base><ctag>adj:sg:nom:f:pos</ctag></lex>
    <lex><base>bity</base><ctag>adj:sg:voc:f:pos</ctag></lex>
    <lex><base>bić</base><ctag>ppas:sg:nom:f:imperf:aff</ctag></lex>
    <lex><base>bić</base><ctag>ppas:sg:voc:f:imperf:aff</ctag></lex>
   </tok>
   <tok>
    <orth>to</orth>
    <lex><base>ten</base><ctag>adj:sg:nom:n:pos</ctag></lex>
    <lex><base>ten</base><ctag>adj:sg:acc:n:pos</ctag></lex>
    <lex><base>ten</base><ctag>adj:sg:voc:n:pos</ctag></lex>
    <lex><base>to</base><ctag>conj</ctag></lex>
   </tok>
   <tok>
    <orth>jak</orth>
    <lex><base>jak</base><ctag>conj</ctag></lex>
    <lex><base>jak</base><ctag>subst:sg:nom:m1</ctag></lex>
    <lex><base>jak</base><ctag>subst:sg:nom:m2</ctag></lex>
    <lex><base>jak</base><ctag>subst:sg:nom:m3</ctag></lex>
    <lex><base>jaka</base><ctag>subst:pl:gen:f</ctag></lex>
   </tok>
   <tok>
    <orth>kosa</orth>
    <lex><base>kos</base><ctag>subst:sg:gen:m2</ctag></lex>
    <lex><base>kos</base><ctag>subst:sg:acc:m2</ctag></lex>
    <lex><base>kosa</base><ctag>subst:sg:nom:f</ctag></lex>
    <lex><base>kosy</base><ctag>adj:sg:nom:f:pos</ctag></lex>
    <lex><base>kosy</base><ctag>adj:sg:voc:f:pos</ctag></lex>
   </tok>
   <tok>
    <orth>nie</orth>
    <lex><base>nie</base><ctag>qub</ctag></lex>
    <lex><base>on</base><ctag>ppron3:sg:acc:n:ter:praep</ctag></lex>
    <lex><base>on</base><ctag>ppron3:pl:acc:m2:ter:praep</ctag></lex>
    <lex><base>on</base><ctag>ppron3:pl:acc:m3:ter:praep</ctag></lex>
    <lex><base>on</base><ctag>ppron3:pl:acc:f:ter:praep</ctag></lex>
    <lex><base>on</base><ctag>ppron3:pl:acc:n:ter:praep</ctag></lex>
   </tok>
   <tok>
    <orth>klepana</orth>
    <lex><base>klepać</base><ctag>ppas:sg:nom:f:imperf:aff</ctag></lex>
    <lex><base>klepać</base><ctag>ppas:sg:voc:f:imperf:aff</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>!</orth>
    <lex><base>!</base><ctag>interp</ctag></lex>
   </tok>
  </chunk>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/tag/manyrules/agr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <chunk type="s">
   <tok>
    <orth>Na</orth>
    <lex><base>na</base><ctag>prep:acc</ctag></lex>
    <lex><base>na</base><ctag>prep:loc</ctag></lex>
   </tok>
   <tok>
    <orth>starym</orth>
    <lex><base>stara</base><ctag>subst:pl:dat:f</ctag></lex>
    <lex><base>stary</base><ctag>adj:pl:dat:f:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:pl:dat:m1:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:pl:dat:m2:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:pl:dat:m3:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:pl:dat:n:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:inst:m1:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:inst:m2:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:inst:m3:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:inst:n:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:loc:m1:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:loc:m2:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:loc:m3:pos</ctag></lex>
    <lex><base>stary</base><ctag>adj:sg:loc:n:pos</ctag></lex>
   </tok>
   <tok>
    <orth>stole</orth>
    <lex><base>stola</base><ctag>subst:pl:acc:f</ctag></lex>
    <lex><base>stola</base><ctag>subst:pl:nom:f</ctag></lex>
    <lex><base>stola</base><ctag>subst:pl:voc:f</ctag></lex>
    <lex><base>stół</base><ctag>subst:sg:loc:m3</ctag></lex>
    <lex><base>stół</base><ctag>subst:sg:voc:m3</ctag></lex>
   </tok>
  </chunk>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/examples/in-xces.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <chunk type="s">
   <tok>
    <orth>Rodzina</orth>
    <lex><base>rodzina</base><ctag>subst:sg:nom:f</ctag></lex>
   </tok>
   <tok>
    <orth>pingwinów</orth>
    <lex><base>pingwin</base><ctag>subst:pl:gen:m2</ctag></lex>
   </tok>
   <tok>
    <orth>obejmuje</orth>
    <lex><base>obejmować</base><ctag>fin:sg:ter:imperf</ctag></lex>
   </tok>
   <tok>
    <orth>gatunki</orth>
    <lex><base>gatunek</base><ctag>subst:pl:nom:m3</ctag></lex>
    <lex><base>gatunek</base><ctag>subst:pl:acc:m3</ctag></lex>
    <lex><base>gatunek</base><ctag>subst:pl:voc:m3</ctag></lex>
   </tok>
   <tok>
    <orth>morskie</orth>
    <lex><base>morski</base><ctag>adj:sg:nom:n:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:sg:acc:n:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:sg:voc:n:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:nom:m2:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:acc:m2:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:voc:m2:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:nom:m3:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:acc:m3:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:voc:m3:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:nom:f:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:acc:f:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:voc:f:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:nom:n:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:acc:n:pos</ctag></lex>
    <lex><base>morski</base><ctag>adj:pl:voc:n:pos</ctag></lex>
   </tok>
   <tok>
    <orth>(</orth>
    <lex><base>(</base><ctag>interp</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>na</orth>
    <lex><base>na</base><ctag>prep:acc</ctag></lex>
    <lex><base>na</base><ctag>prep:loc</ctag></lex>
   </tok>
   <tok>
    <orth>lądzie</orth>
    <lex><base>ląd</base><ctag>subst:sg:loc:m3</ctag></lex>
    <lex><base>ląd</base><ctag>subst:sg:voc:m3</ctag></lex>
   </tok>
   <tok>
    <orth>pojawiają</orth>
    <lex><base>pojawiać</base><ctag>fin:pl:ter:imperf</ctag></lex>
   </tok>
   <tok>
    <orth>się</orth>
    <lex><base>się</base><ctag>qub</ctag></lex>
   </tok>
   <tok>
    <orth>jedynie</orth>
    <lex><base>jedynie</base><ctag>adv:pos</ctag></lex>
   </tok>
   <tok>
    <orth>w</orth>
    <lex><base>w</base><ctag>prep:acc:nwok</ctag></lex>
    <lex><base>w</base><ctag>prep:loc:nwok</ctag></lex>
   </tok>
   <tok>
    <orth>strefie</orth>
    <lex><base>strefa</base><ctag>subst:sg:dat:f</ctag></lex>
    <lex><base>strefa</base><ctag>subst:sg:loc:f</ctag></lex>
   </tok>
   <tok>
    <orth>brzegowej</orth>
    <lex><base>brzegowy</base><ctag>adj:sg:gen:f:pos</ctag></lex>
    <lex><base>brzegowy</base><ctag>adj:sg:dat:f:pos</ctag></lex>
    <lex><base>brzegowy</base><ctag>adj:sg:loc:f:pos</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>)</orth>
    <lex><base>)</base><ctag>interp</ctag></lex>
   </tok>
   <tok>
    <orth>zamieszkujące</orth>
    <lex><base>zamieszkiwać</base><ctag>pact:sg:nom:n:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:sg:acc:n:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:sg:voc:n:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:nom:m2:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:acc:m2:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:voc:m2:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:nom:m3:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:acc:m3:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:voc:m3:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:nom:f:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:acc:f:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:voc:f:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:nom:n:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:acc:n:imperf:aff</ctag></lex>
    <lex><base>zamieszkiwać</base><ctag>pact:pl:voc:n:imperf:aff</ctag></lex>
   </tok>
   <tok>
    <orth>zimne</orth>
    <lex><base>zimny</base><ctag>adj:sg:nom:n:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:sg:acc:n:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:sg:voc:n:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:nom:m2:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:acc:m2:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:voc:m2:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:nom:m3:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:acc:m3:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:voc:m3:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:nom:f:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:acc:f:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:voc:f:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:nom:n:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:acc:n:pos</ctag></lex>
    <lex><base>zimny</base><ctag>adj:pl:voc:n:pos</ctag></lex>
   </tok>
   <tok>
    <orth>morza</orth>
    <lex><base>morze</base><ctag>subst:sg:gen:n</ctag></lex>
    <lex><base>morze</base><ctag>subst:pl:nom:n</ctag></lex>
    <lex><base>morze</base><ctag>subst:pl:acc:n</ctag></lex>
    <lex><base>morze</base><ctag>subst:pl:voc:n</ctag></lex>
   </tok>
   <tok>
    <orth>półkuli</orth>
    <lex><base>półkula</base><ctag>subst:sg:gen:f</ctag></lex>
    <lex><base>półkula</base><ctag>subst:sg:dat:f</ctag></lex>
    <lex><base>półkula</base><ctag>subst:sg:loc:f</ctag></lex>
   </tok>
   <tok>
    <orth>południowej</orth>
    <lex><base>południowy</base><ctag>adj:sg:gen:f:pos</ctag></lex>
    <lex><base>południowy</base><ctag>adj:sg:dat:f:pos</ctag></lex>
    <lex><base>południowy</base><ctag>adj:sg:loc:f:pos</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
   </tok>
  </chunk>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/tag/unify/agreed.out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <chunk type="s">
   <tok>
    <orth>Kobieta</orth>
    <lex><base>kobieta</base><ctag>subst:sg:nom:f</ctag></lex>
   </tok>
   <tok>
    <orth>nie</orth>
    <lex><base>nie</base><ctag>qub</ctag></lex>
  </tok>
   <tok>
    <orth>bita</orth>
    <lex><base>bity</base><ctag>adj:sg:nom:f:pos</ctag></lex>
    <lex><base>bić</base><ctag>ppas:sg:nom:f:imperf:aff</ctag></lex>
   </tok>
   <tok>
    <orth>to</orth>
    <lex><base>to</base><ctag>conj</ctag></lex>
   </tok>
   <tok>
    <orth>jak</orth>
    <lex><base>jak</base><ctag>conj</ctag></lex>
   </tok>
   <tok>
    <orth>kosa</orth>
    <lex><base>kosa</base><ctag>subst:sg:nom:f</ctag></lex>
    <lex><base>kosy</base><ctag>adj:sg:nom:f:pos</ctag></lex>
    <lex><base>kosy</base><ctag>adj:sg:voc:f:pos</ctag></lex>
   </tok>
   <tok>
    <orth>nie</orth>
    <lex><base>nie</base><ctag>qub</ctag></lex>
  </tok>
   <tok>
    <orth>klepana</orth>
    <lex><base>klepać</base><ctag>ppas:sg:nom:f:imperf:aff</ctag></lex>
    <lex><base>klepać</base><ctag>ppas:sg:voc:f:imperf:aff</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>!</orth>
    <lex><base>!</base><ctag>interp</ctag></lex>
   </tok>
  </chunk>
 </chunk>
</chunkList>
</cesAna>
