=== stasiekz/PolishReadabilityChecker/third_party/corpus2/doc/xcesAnaIPI.dtd
<!--                                                          -->
<!--                                                          -->
<!--                Corpus Encoding Standard                  -->
<!--                                                          -->
<!--                          CES                             -->
<!--                                                          -->
<!--         Encoding conventions for annotated data          -->
<!--                                                          -->
<!--                                                          -->
<!--         Modified for the IPI PAN corpus                  -->
<!--         Version IPI-1.6                                  -->
<!--                                                          -->
<!--                                                          -->
<!--                                                          -->
<!--                                                          -->
<!--                                                          -->
<!--
     Original Date: 1996/08/05 19:07:30 
     Original Revision: 1.11 
     Author of 1.11: Patrice Bonhomme

     $Id: xcesAnaIPI.dtd,v 1.1.1.1 2007/11/08 15:26:49 adamp Exp $
*    $Log: xcesAnaIPI.dtd,v $
*    Revision 1.1.1.1  2007/11/08 15:26:49  adamp
*    Spejd
*
*    Revision 1.1  2007/10/20 13:11:39  adamp
*    *** empty log message ***
*
*    Revision 1.6  2006/06/03 12:53:28  adamp
*    Updated version number of xcesAnaIPI.dtd.
*
*    Revision 1.5  2006/06/03 12:45:41  adamp
*    Simplified.
*
*    Revision 1.2  2006/06/03 12:33:13  adamp
*    Changed name from doc2ana.sh to index.morph.sh.
*
*    Revision 1.1  2006/06/03 11:43:59  adamp
*    *** empty log message ***
*
*    Revision 1.4  2006/02/03 14:00:50  adamp
*    Corresponding change of version number (to 1.3).
*
*    Revision 1.3  2006/02/03 13:59:03  adamp
*    Changed (tok|ns)+ to (tok|ns)* - let's hope that Poliqarp can deal with empty chunks...
*
*    Revision 1.2  2004-03-16 19:00:48  adamp
*    ATTLIST for lex was defined twice, so I've removed the first
*    definition.  This caused version change to IPI-1.2 (maybe it shouldn't
*    have, but just to be on the safe side).
*
*    Revision 1.1.1.1  2004/03/10 19:21:29  adamp
*    x2XCES converters for the IPI PAN corpus
*
*    Revision 1.14  2004/03/01 16:00:48  adamp
*    New version: 'IPI-1.1'.
*
*    Revision 1.13  2004/03/01 15:58:05  adamp
*    Only typos in comments.
*
*    Revision 1.12  2004/03/01 13:58:55  adamp
*    PB's modifications: the value of 'lang' is CDATA now, and the locus of
*    xmlns:xlink changed.
*
*    Revision 1.11  2004/03/01 10:55:46  adamp
*    PB's modifications.
*
*    Revision 1.11  2004/03/01 01:15:30  piotr
*    Added fully specified xmlns:xlink (to make the xlink namespace legal)
*    and the xml:base attribute for use in <chunkList>
*
*    $Log: xcesAnaIPI.dtd,v $
*    Revision 1.1.1.1  2007/11/08 15:26:49  adamp
*    Spejd
*
*    Revision 1.1  2007/10/20 13:11:39  adamp
*    *** empty log message ***
*
*    Revision 1.6  2006/06/03 12:53:28  adamp
*    Updated version number of xcesAnaIPI.dtd.
*
*    Revision 1.5  2006/06/03 12:45:41  adamp
*    Simplified.
*
*    Revision 1.2  2006/06/03 12:33:13  adamp
*    Changed name from doc2ana.sh to index.morph.sh.
*
*    Revision 1.1  2006/06/03 11:43:59  adamp
*    *** empty log message ***
*
*    Revision 1.4  2006/02/03 14:00:50  adamp
*    Corresponding change of version number (to 1.3).
*
*    Revision 1.3  2006/02/03 13:59:03  adamp
*    Changed (tok|ns)+ to (tok|ns)* - let's hope that Poliqarp can deal with empty chunks...
*
*    Revision 1.2  2004-03-16 19:00:48  adamp
*    ATTLIST for lex was defined twice, so I've removed the first
*    definition.  This caused version change to IPI-1.2 (maybe it shouldn't
*    have, but just to be on the safe side).
*
*    Revision 1.1.1.1  2004/03/10 19:21:29  adamp
*    x2XCES converters for the IPI PAN corpus
*
*    Revision 1.14  2004/03/01 16:00:48  adamp
*    New version: 'IPI-1.1'.
*
*    Revision 1.13  2004/03/01 15:58:05  adamp
*    Only typos in comments.
*
*    Revision 1.12  2004/03/01 13:58:55  adamp
*    PB's modifications: the value of 'lang' is CDATA now, and the locus of
*    xmlns:xlink changed.
*
*    Revision 1.11  2004/03/01 10:55:46  adamp
*    PB's modifications.
*
*    Revision 1.10  2004/02/27 22:38:09  adamp
*    Wyrzucone atrybuty xml..., dodany element <ns> (no space).
*
*    Revision 1.9  2004/02/25 23:00:34  adamp
*    Changes in comments only.
*
*    Revision 1.8  2004/02/25 16:36:50  adamp
*    Re-introducing various modifications by PB.
*
*    Revision 1.7  2004/02/22 19:10:58  adamp
*    Only minor changes in comments.
*
*    Revision 1.6  2004/02/12 15:43:47  adamp
*    *** empty log message ***
*
*    Revision 1.5  2004/02/11 22:38:47  adamp
*    Typo.
*
*    Revision 1.4  2004/02/10 17:51:51  adamp
*    Wersja zawierająca <par> (tak jak w oryginalnym XCES, inaczej niż w
*    wersji Piotrka Bańskiego).
*
*    Revision 1.3  2004/02/10 17:18:09  adamp
*    No real change, just testing CVS.
*
*    Revision 1.2  2004/02/10 17:17:30  adamp
*    Added xmlns.

  This is a modification of the original CES DTD designed for use with
  the IPI PAN Corpus.  Created by Adam Przepiórkowski, on the basis of
  ealier modifications by Piotr Bański, cf. PB (who's the author of
  the vast majority of changes, as of 9th February 2004).

                                                              -->

<!--                  Global attributes                       -->

<!-- Modification by Piotr Bański: -->
<!-- The addition of the xlink:href attribute below. -->
<!-- PB, 010304: 'lang IDREFS' zmienione na 'lang CDATA'. -->
<!ENTITY % a.global '
	id		ID                  #IMPLIED
	n		CDATA               #IMPLIED
	xml:lang	CDATA               #IMPLIED
        xlink:href      CDATA               #IMPLIED
	lang		CDATA               #IMPLIED'		>

<!-- Modification by PB: adding xlink:... attributes.  Also xml:base.  -->
<!ENTITY % a.ana '%a.global;
        xml:base        CDATA               #IMPLIED
	type		CDATA               #IMPLIED
	wsd		CDATA               #IMPLIED'		>
 

<!ELEMENT cesAna	(cesHeader?, chunkList)			>
<!-- Modification by PB: xmlns:xlink.  -->
<!ATTLIST cesAna	%a.ana;                         
	doc		CDATA		#IMPLIED
        xmlns:xlink     CDATA           "http://www.w3.org/1999/xlink"
	version		CDATA		#REQUIRED		>

<!ENTITY % xces.header SYSTEM 'xheaderIPI.elt'                       >
%xces.header;

<!ELEMENT chunkList     (chunk)+                           >
<!ATTLIST chunkList          %a.ana;                            >

<!-- AP: Chunks contain either smaller chunks or tokens + no white space -->
<!-- markers. -->
<!-- AP: Changed + to * - let's hope that Poliqarp can deal with empty chunks... -->
<!ELEMENT chunk         ((tok|ns)* | chunk+)                 >
<!-- PB's modification: no attributes 'doc', 'from' and 'to'. -->
<!ATTLIST chunk              %a.ana;                   >

<!-- AP: elements 'par' and 's' disappear; instead, there chunks of type -->
<!-- 's' and 'p'. --> 


<!-- PB's modification (and comment) -->
<!--
threw out the disamb element - it will be an attribute now
more simplification:
eliminated msds, cause we use ctags for them; guarantee at least one lex;
-->
<!ELEMENT tok           (orth, lex+)              >

<!-- PB's modification: -->
<!-- Removed attributes 'from' and 'to'. -->
<!ATTLIST tok                %a.ana;
          class              CDATA               #IMPLIED >

<!-- AP: Adding a 'no white space between tokens' marker: -->
<!ELEMENT ns           EMPTY                              >

<!ELEMENT orth          (#PCDATA)                          >
<!ATTLIST orth               %a.ana;                            >

<!-- PB's modification (and comment): -->
<!--
msd removed for simplicity, we use msds as ctags
and ctags are grouped around a unique base (note: uniqueness of the base is not
guaranteed by the DTD)
-->
<!ELEMENT lex           (base, ctag+)                 >
<!-- AP: gotten rid of spurious attlist for lex. -->
<!-- <!ATTLIST lex                %a.ana;                      > -->


<!-- Modification by Piotr Bański: -->
<!-- duplicated 'disamb' with 'human', indicating hand-checked bits -->
<!ATTLIST lex                %a.ana;
          disamb        (1 | 0)                   #IMPLIED
          human         (1 | 0)                   #IMPLIED         >

<!ELEMENT base          (#PCDATA)                          >
<!ATTLIST base               %a.ana;                            >

<!-- The msd element removed (by PB). -->

<!-- PB's modification and comment: -->
<!-- added the disamb attribute here -->
<!ELEMENT ctag          (#PCDATA)                          >
<!ATTLIST ctag               %a.ana;                            >

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/match/head/cclmatch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <sentence>
   <tok>
    <orth>Tu</orth>
    <lex><base>tu</base><ctag>qub</ctag></lex>
   </tok>
   <tok>
    <orth>jest</orth>
    <lex><base>być</base><ctag>verb</ctag></lex>
   </tok>
   <tok>
    <orth>czarny</orth>
    <lex><base>czarny</base><ctag>adj</ctag></lex>
   </tok>
   <tok>
    <orth>błyszczący</orth>
    <lex><base>błyszczeć</base><ctag>adj</ctag></lex>
   </tok>
   <tok>
    <orth>głośnik</orth>
    <lex><base>głośnik</base><ctag>noun</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
   </tok>
  </sentence>
  <sentence>
   <tok>
    <orth>Tam</orth>
    <lex><base>tam</base><ctag>qub</ctag></lex>
   </tok>
   <tok>
    <orth>jest</orth>
    <lex><base>być</base><ctag>verb</ctag></lex>
   </tok>
   <tok>
    <orth>nowa</orth>
    <lex><base>nowy</base><ctag>adj</ctag></lex>
   </tok>
   <tok>
    <orth>pompa</orth>
    <lex><base>pompa</base><ctag>noun</ctag></lex>
   </tok>
   <tok>
    <orth>próżniowa</orth>
    <lex><base>próżniowy</base><ctag>adj</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
   </tok>
  </sentence>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/match/text/cclmatch1.out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <sentence>
   <tok>
    <orth>Sp.</orth>
    <lex><base>sp.</base><ctag>subst:sg:nom:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:gen:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:dat:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:acc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:inst:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:loc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:voc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:nom:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:gen:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:dat:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:acc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:inst:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:loc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:voc:f</ctag></lex>
    <ann chan="Co" head="1">1</ann>
   </tok>
   <tok>
    <orth>z</orth>
    <lex><base>z</base><ctag>prep:gen:nwok</ctag></lex>
    <lex><base>z</base><ctag>prep:inst:nwok</ctag></lex>
    <lex><base>z</base><ctag>qub</ctag></lex>
    <ann chan="Co">1</ann>
   </tok>
   <tok>
    <orth>o</orth>
    <lex><base>o</base><ctag>prep:acc</ctag></lex>
    <lex><base>o</base><ctag>prep:loc</ctag></lex>
    <ann chan="Co">1</ann>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
    <ann chan="Co">1</ann>
   </tok>
   <ns/>
   <tok>
    <orth>o</orth>
    <lex><base>o</base><ctag>prep:acc</ctag></lex>
    <lex><base>o</base><ctag>prep:loc</ctag></lex>
    <ann chan="Co">1</ann>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
    <ann chan="Co">1</ann>
   </tok>
   <tok>
    <orth>Sp.</orth>
    <lex><base>sp.</base><ctag>subst:sg:nom:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:gen:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:dat:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:acc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:inst:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:loc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:sg:voc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:nom:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:gen:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:dat:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:acc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:inst:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:loc:f</ctag></lex>
    <lex><base>sp.</base><ctag>subst:pl:voc:f</ctag></lex>
    <ann chan="Co">0</ann>
   </tok>
   <tok>
    <orth>z</orth>
    <lex><base>z</base><ctag>prep:gen:nwok</ctag></lex>
    <lex><base>z</base><ctag>prep:inst:nwok</ctag></lex>
    <lex><base>z</base><ctag>qub</ctag></lex>
    <ann chan="Co">0</ann>
   </tok>
   <tok>
    <orth>o</orth>
    <lex><base>o</base><ctag>prep:acc</ctag></lex>
    <lex><base>o</base><ctag>prep:loc</ctag></lex>
    <ann chan="Co">0</ann>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
    <ann chan="Co">0</ann>
   </tok>
   <ns/>
   <tok>
    <orth>ooo</orth>
    <lex><base>ooo</base><ctag>qub</ctag></lex>
    <ann chan="Co">0</ann>
   </tok>
  </sentence>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/match/single_tok/cclmatch1.out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk id="ch1" type="p">
  <sentence>
   <tok>
    <orth>To</orth>
    <lex><base>ten</base><ctag>adj:sg:nom:n:pos</ctag></lex>
    <lex><base>ten</base><ctag>adj:sg:acc:n:pos</ctag></lex>
    <lex><base>to</base><ctag>conj</ctag></lex>
    <lex><base>to</base><ctag>pred</ctag></lex>
    <lex><base>to</base><ctag>qub</ctag></lex>
    <lex><base>to</base><ctag>subst:sg:nom:n</ctag></lex>
    <lex><base>to</base><ctag>subst:sg:acc:n</ctag></lex>
    <lex><base>to</base><ctag>subst:sg:voc:n</ctag></lex>
    <ann chan="N_NOM" head="1">1</ann>
   </tok>
   <tok>
    <orth>jest</orth>
    <lex><base>być</base><ctag>fin:sg:ter:imperf</ctag></lex>
    <ann chan="N_NOM">0</ann>
   </tok>
   <tok>
    <orth>wyżyna</orth>
    <lex><base>wyżyna</base><ctag>subst:sg:nom:f</ctag></lex>
    <ann chan="N_NOM" head="1">2</ann>
   </tok>
   <tok>
    <orth>pies</orth>
    <lex><base>pies</base><ctag>subst:sg:nom:m2</ctag></lex>
    <ann chan="N_NOM" head="1">3</ann>
   </tok>
  </sentence>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/data/agreement/nadzieje.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <chunk type="s">
   <tok>
    <orth>Nasze</orth>
    <lex><base>nasz</base><ctag>adj:sg:nom:n:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:sg:acc:n:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:sg:voc:n:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:nom:m2:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:acc:m2:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:voc:m2:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:nom:m3:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:acc:m3:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:voc:m3:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:nom:f:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:acc:f:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:voc:f:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:nom:n:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:acc:n:pos</ctag></lex>
    <lex><base>nasz</base><ctag>adj:pl:voc:n:pos</ctag></lex>
   </tok>
   <tok>
    <orth>nadzieje</orth>
    <lex><base>nadziać</base><ctag>fin:sg:ter:perf</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:nom:f</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:acc:f</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:voc:f</ctag></lex>
   </tok>
   <tok>
    <orth>wspaniałe</orth>
    <lex><base>wspaniały</base><ctag>adj:sg:nom:n:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:sg:acc:n:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:sg:voc:n:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:nom:m2:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:acc:m2:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:voc:m2:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:nom:m3:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:acc:m3:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:voc:m3:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:nom:f:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:acc:f:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:voc:f:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:nom:n:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:acc:n:pos</ctag></lex>
    <lex><base>wspaniały</base><ctag>adj:pl:voc:n:pos</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>;</orth>
    <lex><base>;</base><ctag>interp</ctag></lex>
   </tok>
   <tok>
    <orth>ona</orth>
    <lex><base>on</base><ctag>ppron3:sg:nom:f:ter</ctag></lex>
   </tok>
   <tok>
    <orth>nadzieje</orth>
    <lex><base>nadziać</base><ctag>fin:sg:ter:perf</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:nom:f</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:acc:f</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:voc:f</ctag></lex>
   </tok>
   <tok>
    <orth>pierwsza</orth>
    <lex><base>pierwsza</base><ctag>subst:sg:nom:f</ctag></lex>
    <lex><base>pierwszy</base><ctag>adj:sg:nom:f:pos</ctag></lex>
    <lex><base>pierwszy</base><ctag>adj:sg:voc:f:pos</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>;</orth>
    <lex><base>;</base><ctag>interp</ctag></lex>
   </tok>
   <tok>
    <orth>oni</orth>
    <lex><base>on</base><ctag>ppron3:pl:nom:m1:ter</ctag></lex>
   </tok>
   <tok>
    <orth>nadzieje</orth>
    <lex><base>nadziać</base><ctag>fin:sg:ter:perf</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:nom:f</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:acc:f</ctag></lex>
    <lex><base>nadzieja</base><ctag>subst:pl:voc:f</ctag></lex>
   </tok>
   <tok>
    <orth>pierwsi</orth>
    <lex><base>pierwszy</base><ctag>adj:pl:nom:m1:pos</ctag></lex>
    <lex><base>pierwszy</base><ctag>adj:pl:voc:m1:pos</ctag></lex>
   </tok>
  </chunk>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/tag/relabel-enc/suger.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <chunk type="s">
   <tok>
    <orth>Jedzenie</orth>
    <lex><base>jedzenie</base><ctag>subst:sg:acc:n</ctag></lex>
    <lex><base>jedzenie</base><ctag>subst:sg:nom:n</ctag></lex>
    <lex><base>jedzenie</base><ctag>subst:sg:voc:n</ctag></lex>
    <lex><base>jeść</base><ctag>ger:sg:acc:n:imperf:aff</ctag></lex>
    <lex><base>jeść</base><ctag>ger:sg:nom:n:imperf:aff</ctag></lex>
    <lex><base>jeść</base><ctag>ger:sg:voc:n:imperf:aff</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>,</orth>
    <lex><base>,</base><ctag>interp</ctag></lex>
   </tok>
   <tok>
    <orth>siedzenie</orth>
    <lex><base>siedzenie</base><ctag>subst:sg:acc:n</ctag></lex>
    <lex><base>siedzenie</base><ctag>subst:sg:nom:n</ctag></lex>
    <lex><base>siedzenie</base><ctag>subst:sg:voc:n</ctag></lex>
    <lex><base>siedzieć</base><ctag>ger:sg:acc:n:imperf:aff</ctag></lex>
    <lex><base>siedzieć</base><ctag>ger:sg:nom:n:imperf:aff</ctag></lex>
    <lex><base>siedzieć</base><ctag>ger:sg:voc:n:imperf:aff</ctag></lex>
   </tok>
   <tok>
    <orth>i</orth>
    <lex><base>i</base><ctag>conj</ctag></lex>
   </tok>
   <tok>
    <orth>drzewo</orth>
    <lex><base>drzewo</base><ctag>subst:sg:acc:n</ctag></lex>
    <lex><base>drzewo</base><ctag>subst:sg:nom:n</ctag></lex>
    <lex><base>drzewo</base><ctag>subst:sg:voc:n</ctag></lex>
   </tok>
  </chunk>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/data/agreement/mamut.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <chunk type="s">
   <tok>
    <orth>Wielki</orth>
    <lex><base>wielki</base><ctag>adj:sg:nom:m1:pos</ctag></lex>
    <lex><base>wielki</base><ctag>adj:sg:voc:m1:pos</ctag></lex>
    <lex><base>wielki</base><ctag>adj:sg:nom:m2:pos</ctag></lex>
    <lex><base>wielki</base><ctag>adj:sg:voc:m2:pos</ctag></lex>
    <lex><base>wielki</base><ctag>adj:sg:nom:m3:pos</ctag></lex>
    <lex><base>wielki</base><ctag>adj:sg:acc:m3:pos</ctag></lex>
   </tok>
   <tok>
    <orth>włochaty</orth>
    <lex><base>włochaty</base><ctag>adj:sg:nom:m1:pos</ctag></lex>
    <lex><base>włochaty</base><ctag>adj:sg:voc:m1:pos</ctag></lex>
    <lex><base>włochaty</base><ctag>adj:sg:nom:m2:pos</ctag></lex>
    <lex><base>włochaty</base><ctag>adj:sg:voc:m2:pos</ctag></lex>
    <lex><base>włochaty</base><ctag>adj:sg:nom:m3:pos</ctag></lex>
    <lex><base>włochaty</base><ctag>adj:sg:acc:m3:pos</ctag></lex>
   </tok>
   <tok>
    <orth>mamut</orth>
    <lex><base>mamut</base><ctag>subst:sg:nom:m2</ctag></lex>
   </tok>
   <tok>
    <orth>zjadł</orth>
    <lex><base>zjeść</base><ctag>praet:sg:m1:perf</ctag></lex>
    <lex><base>zjeść</base><ctag>praet:sg:m2:perf</ctag></lex>
    <lex><base>zjeść</base><ctag>praet:sg:m3:perf</ctag></lex>
   </tok>
   <tok>
    <orth>kość</orth>
    <lex><base>kość</base><ctag>subst:sg:nom:f</ctag></lex>
    <lex><base>kość</base><ctag>subst:sg:acc:f</ctag></lex>
   </tok>
   <tok>
    <orth>nawet</orth>
    <lex><base>nawet</base><ctag>qub</ctag></lex>
   </tok>
   <tok>
    <orth>smaczną</orth>
    <lex><base>smaczny</base><ctag>adj:sg:acc:f:pos</ctag></lex>
    <lex><base>smaczny</base><ctag>adj:sg:inst:f:pos</ctag></lex>
   </tok>
   <ns/>
   <tok>
    <orth>.</orth>
    <lex><base>.</base><ctag>interp</ctag></lex>
   </tok>
  </chunk>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/tests/rules-data/tag/select/psykoty.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd">
<cesAna xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" type="lex disamb">
<chunkList>
 <chunk>
  <chunk type="s">
   <tok>
    <orth>Duże</orth>
    <lex><base>duży</base><ctag>adj:pl:acc:f:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:acc:m2:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:acc:m3:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:acc:n:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:nom:f:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:nom:m2:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:nom:m3:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:nom:n:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:voc:f:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:voc:m2:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:voc:m3:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:pl:voc:n:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:sg:acc:n:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:sg:nom:n:pos</ctag></lex>
    <lex><base>duży</base><ctag>adj:sg:voc:n:pos</ctag></lex>
   </tok>
   <tok>
    <orth>psy</orth>
    <lex><base>pies</base><ctag>subst:pl:acc:m2</ctag></lex>
    <lex><base>pies</base><ctag>subst:pl:nom:m2</ctag></lex>
    <lex><base>pies</base><ctag>subst:pl:voc:m2</ctag></lex>
   </tok>
   <tok>
    <orth>i</orth>
    <lex><base>i</base><ctag>conj</ctag></lex>
   </tok>
   <tok>
    <orth>koty</orth>
    <lex><base>kot</base><ctag>subst:pl:acc:m2</ctag></lex>
    <lex><base>kot</base><ctag>subst:pl:nom:m1</ctag></lex>
    <lex><base>kot</base><ctag>subst:pl:nom:m2</ctag></lex>
    <lex><base>kot</base><ctag>subst:pl:voc:m1</ctag></lex>
    <lex><base>kot</base><ctag>subst:pl:voc:m2</ctag></lex>
    <lex><base>kota</base><ctag>subst:pl:acc:f</ctag></lex>
    <lex><base>kota</base><ctag>subst:pl:nom:f</ctag></lex>
    <lex><base>kota</base><ctag>subst:pl:voc:f</ctag></lex>
    <lex><base>kota</base><ctag>subst:sg:gen:f</ctag></lex>
    <lex><base>koty</base><ctag>subst:pl:acc:n</ctag></lex>
    <lex><base>koty</base><ctag>subst:pl:nom:n</ctag></lex>
    <lex><base>koty</base><ctag>subst:pl:voc:n</ctag></lex>
   </tok>
  </chunk>
 </chunk>
</chunkList>
</cesAna>

=== stasiekz/PolishReadabilityChecker/third_party/wccl/libmwereader/tests/data/test1.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE cesAna SYSTEM "xcesAnaIPI.dtd"><cesAna type="pre_morph" version="PWR 0.1" xmlns:xlink="http://www.w3.org/1999/xlink"><chunkList xml:base="text.xml">
<chunk type="p" xlink:href="#dv1p0">Chrostowski nie dostrzega przejawów dobrej woli, także po stronie żydowskiej.</chunk>
<chunk type="p" xlink:href="#dv1p1">Zrazu delikatnie - gdy ludzie mijają się na klatce schodowej, oprócz rytualnego "dzień dobry" wymieniają uwagi o brzydkim zapachu.</chunk>
<chunk type="p" xlink:href="#dv1p1">Zrazu delikatnie - gdy ludzie mijają się na klatce schodowej, oprócz rytualnego "dobry dzień" wymieniają uwagi o brzydkim zapachu.</chunk>
<chunk type="p" xlink:href="#dv1p1">Projekt rozporządzenia Ministra Edukacji Narodowej w sprawie podstaw programowych kształcenia w zawodach: górnik eksploatacji podziemnej, górnik odkrywkowej eksploatacji złóż, monter instalacji gazowych, monter instrumentów całkowicie muzycznych, monter sieci komunalnych, stolarz, technik hydrolog, technik instrumentów muzycznych, technik meteorolog i technik papiernictwa Projekt rozporządzenia Ministra Edukacji Narodowej w sprawie sposobu i trybu organizowania indywidualnego obowiązkowego rocznego przygotowania przedszkolnego i indywidualnego nauczania dzieci i młodzieży Projekt rozporządzenia Ministra Edukacji Narodowej w sprawie rodzajów innych form wychowania przedszkolnego, warunków tworzenia i organizowania tych form oraz sposobu ich działania Projekt rozporządzenia Ministra Edukacji Narodowej w sprawie rodzajów innych form wychowania przedszkolnego, warunków tworzenia i organizowania tych form oraz sposobu ich działania.</chunk>
<chunk type="p" xlink:href="#dv1p1">Pozycja, mimo iż dotyczy trudnych zagadnień, zawiera jasne i klarowne pytania, zrozumiałe dla wszystkich tych, którzy zajmują się immunologią z racji studiów, pracy nie całkiem naukowej czy zawodowej.</chunk>
<chunk type="p" xlink:href="#dv1p1">Pozycja, mimo iż dotyczy trudnych zagadnień, zawiera jasne i klarowne pytania, zrozumiałe dla wszystkich tych, którzy zajmują się immunologią z racji studiów, naukowej nie całkiem pracy czy zawodowej.</chunk>
<chunk type="p" xlink:href="#dv1p1">Pozycja, mimo iż dotyczy trudnych zagadnień, zawiera jasne i klarowne pytania, zrozumiałe dla wszystkich tych, którzy zajmują się immunologią z racji studiów, pracy z natury naukowej czy zawodowej.</chunk>
<chunk type="p" xlink:href="#dv1p1">Pozycja, mimo iż dotyczy trudnych zagadnień, zawiera jasne i klarowne pytania, zrozumiałe dla wszystkich tych, którzy zajmują się immunologią z racji studiów, naukowej z natury nie całkiem pracy czy zawodowej.</chunk>
</chunkList></cesAna>
